# Generated by Django 5.0.6 on 2024-05-14 19:59

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='placeholder', max_length=255, null=True, verbose_name='image'),
        ),
    ]
